Issues misconfigured
KeYProject/key pull request #3003
Opened 2023-01-30 17:40 UTC by wadoon

Due to missing issue templates and misconfiguration, nobody can currently create an issue. 

This commit fixes this, and also repairs the link to the FAQs.

2023-01-30 18:02 UTC, mattulbrich commented
Hang on.

I think it would be a very good idea that we use templates instead of free text for bug reports. @WolframPfeifer said he would look into this soon and provide templates (or even forms)

2023-01-30 18:10 UTC, mi-ki commented
I fully agree with @mattulbrich on this point. Starting the new process with (allowing for) chaotic issue reporting does not appear sensible to me. Hence, this is not a misconfiguration in my eyes.

2023-02-01 20:15 UTC, wadoon commented
> Hang on.
> 
> I think it would be a very good idea that we use templates instead of free text for bug reports. @WolframPfeifer said he would look into this soon and provide templates (or even forms)

The creation of blank issues is not that bad. I am not aware when #3004 will be ready, but currently it is not possible to create an issue! And until #3004, we should just allow it.

The difference is a small hint at the end of the list, that blank issues are allowed, [see here](https://github.com/wadoon/key-playground/issues/new/choose). 

On the other side, "issue templates" do not guarantee anything. The user can delete everything in the issue and just start writing own unstructured reports.

2023-02-01 21:30 UTC, mi-ki commented on .github/ISSUE_TEMPLATE/config.yml
> +blank_issues_enabled: true
Blank issues are not a sensible idea for a structured development process.

2023-02-01 21:32 UTC, mi-ki requested changes
The proposed pull request is neither a fix nor an improvement. Instead, e.g., issue forms with mandatory fields should be used.

2023-02-01 22:31 UTC, mattulbrich commented
I've made a suggestion to #3004 and think we can merge that now ... it'll do for the moment. ...

2023-02-02 20:07 UTC, closed without merging