Use KeYParser.g4 for parsing proof scripts
KeYProject/key pull request #3021
Opened 2023-02-05 14:33 UTC by wadoon

This MR get rid of the hand-written parser for proof scripts and uses a few rules in KeYParser.g4 instead.

Since the start of proof scripts, the KeYParser has changed and became an ANTLR4 grammar. This allows us to easily write grammar for our proof scripts. (Or just copy the few rules from Sarah and mine proof script parser). This eliminates the handwritten proof script parser with the following benefits:

1. Proof Scripts are a first-class citizen in KeY files. You do not need to put your proof script into a string literal:
   ```
   \proofscript {
       andLeft;
       andRight;  
       rule a ==> b;
   }
   ```

   
   Please note an ambiguity in the grammar: `rule b ==> c` could either be interpreted as a command with one or two arguments: 
   1.  a semi-sequent `b ==>` and a term `c`, or 
   2. a sequent ` b ==> c`.
   
   Use quotes or better backticks to clarify these situations.

2. Earlier and better syntax errors. (during reading the KeY file)

3. Proper data structure: no triple of strings are pushed through KeY.

4. You do not need to put your arguments in quotes. Literals, terms and sequents are parsed. 

Tried to achieve backwards-compatibility. If the proof script is given as a string, the parsing is delayed until the execution. The same is valid for arguments. 

Note there is a difference between `f(x)` and "f(x)". The first one is parsed directly as a term and cannot be passed to non-term arguments. The second one is parsed as a string. By meta-information on commands, the string is lazily converted to a term if necessary.

2023-02-05 15:04 UTC, mattulbrich commented
I agree that the current parser is more a proof-of-concept solution than future-proof.

However: With many ideas around proof scripts, which should possibly discuss how this should go now: The script debugger has its ways of communicating to the server, scripts can be in .key files, they were at a point interactively editable, and the plan is to have them in JML code. Do they all go to the same background linear script language or is the base language itself more than a sequence of commands?

@WolframPfeifer @jwiesler

2025-01-20 19:31 UTC, mattulbrich reviewed
First round of review. Some feedback. Could not review the whole thing.

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/antlr4/KeYParser.g4
> +  | seq;
I really do not like the ambiguity.
Can we make this IDENTIFIER without ticks and any composed term/seq in ticks?
I would prefer single ticks compared to back ticks. I do not think we need single-character parameters (and if: Use strings ...)

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/api/ProofApi.java
Documentation would be really helpful. Especially since this is a public API class.
This goes for the class and the methods.

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/control/KeYEnvironment.java
> +    private final KeyAst.@Nullable ProofScript proofScript;
`A.@NonNull B`
Oh dear. This is the Java syntax? Not really nice. Perhaps import ProofScript to avoid this ugly syntax. ...

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AbstractCommand.java
Is this a template or an abstract class? If the former, explain what implementors need to do. If the later, explain what needs to be done to inherit ... No chance to use it w/o doc,

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
Don't know who wrote this, but definitely needs doc.

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
> +    public String getDocumentation() {
That xml file does not seem to be the best spot to store documentation.
Can we actually store it here inline, possibly using multiline strings?
That would actually kill two birds with one stone: Developer (javadoc-) documentation and user documentation.

We could also make this an annotation to the Parameters class for each command, and have the parameters themselves also receive that annotation. ...

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
What does this command do? Why can most of the code be remoived?

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/ExprEvaluator.java
Please add documentation to the class.

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/LetCommand.java
> + * weigl: add new parameter {@code force} to override bindings.
This needs more explanation.

2025-01-20 19:31 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/LetCommand.java
> +            if (key.startsWith("#") && key.equals("force")) {
This is `if(false)`

2025-01-20 19:33 UTC, mattulbrich commented
Reply to me-from-the past:
> However: With many ideas around proof scripts, which should possibly discuss how this should go now: The script debugger has its ways of communicating to the server, scripts can be in .key files, they were at a point interactively editable, and the plan is to have them in JML code. Do they all go to the same background linear script language or is the base language itself more than a sequence of commands?

After implementing a/the script language for JML: This was compiled down to a linear script. So it seems that a list of individual proof commands looks like the right level of abstraction.

2025-01-20 20:04 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
I also do not know who wrote it. But `git` blames you on 04.01.2022. 

I guess the command `onAll <cmd>` applies on all open goals the command `<cmd>`.

I did the following: proof commands can also have a script block as the last parameter:

```
onAll <parameter as usual> {   command1; command2 }
```

And the commands can decide what to do with it. This is a rather easy trick, but allows to implement the `repeat`, `foreach`/`onAll` or `try` blocks etc. of Sarah's scripts.

2025-01-20 20:08 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/nparser/KeyAst.java
> +                        ctx.getCharPositionInLine() + 1);
This preserves the positional information by setting the string to the correct position (line/column) and I added the preservation of the source name.

2025-01-20 20:19 UTC, wadoon commented on key.core/src/main/antlr4/KeYParser.g4
> +  | seq;
> I really do not like the ambiguity.

Not my language. 

>  Can we make this IDENTIFIER without ticks and any composed term/seq in ticks?

What do you mean by this IDENTIFIER?

In `macro tryclose`, the `tryclose` is still evaluated as a string and not sent to the expression evaluation. This adds unnecessary complexity. 

> I would prefer single ticks compared to back ticks

* single quotes `'` are often used currently as string quotes in proof scripts
* backticks are only necessary to avoid ambiguous situations: `command p=2` could be a formula or the parameter `p` to be 2.

> (and if: Use strings ...)

No. The advantage of separation is that the parser is eager to give feedback on syntactical correctness. Otherwise, these errors appears only on evaluation of commands.

2025-01-20 20:20 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/api/ProofApi.java
This class is old, and will be removed with PR on the Rest API.

2025-01-20 20:43 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
> +    public String getDocumentation() {
One of the problems of Java. IMHO, it seems that we auto-inspection, like in PSDBG. So I would rather drop this method in favor of Javadoc or a website. 

For know, I removed the XML and `DescriptionFacade`.

2025-01-20 20:47 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/control/KeYEnvironment.java
> +    private final KeyAst.@Nullable ProofScript proofScript;
Yes, this is the Java syntax, which is required to avoid compiler errors.

2025-01-20 20:47 UTC, wadoon commented on key.core/src/main/java/de/uka/ilkd/key/macros/scripts/AllCommand.java
> +    public String getDocumentation() {
https://keyproject.github.io/key-docs/workbench/Proof%20Scripts/commands/

2025-01-21 11:30 UTC, wadoon commented
Where is sonarqube?

2025-01-29 21:34 UTC, wadoon commented
> After implementing a/the script language for JML: This was compiled down to a linear script. So it seems that a list of individual proof commands looks like the right level of abstraction.

This PR gives the current state a proper syntax in alignment with the KeY grammar. So the list of proof commands are still preserved. Giving the commands the possibility to receive a block of sub-commands arises from your `AllCommand` and allows future extensions w/o needing syntax changes.

We need a quoting symbol for terms for the ambiguities, `"` is used for string values, and `'` is also occupied (do we use it for char literals?). So backticks `\`` are a possible option, but we can also go for parentheses, e.g., `let @a=(f(x))` etc. I do not care.

2025-02-22 10:17 UTC, mattulbrich requested changes

2025-02-22 10:17 UTC, mattulbrich commented on key.ui/examples/heap/quicksort/sort.key
> +\proofScript {
This example was intended to show that scripts can also be in external files.
It should remain like that to show the feature.

2025-02-22 10:17 UTC, mattulbrich commented on key.ui/examples/heap/quicksort/split.key
> +	instantiate hide var=jv with=j_0;
I think this is confusing to users. When to use which quotes. Or not use them. ...

2025-02-22 10:17 UTC, mattulbrich commented on key.core/src/test/resources/de/uka/ilkd/key/macros/scripts/cases.yml
This is an unrelated change.
I'd rather like to keep the original structure with many individual files.
(yaml or the original format which did a good job)

2025-02-22 10:17 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/wdFormulaRules.key
important catch, but not related to the pr.

2025-02-22 10:20 UTC, mattulbrich commented
There seem to be accidental artifacts of other PRs in this one.

The old principle was: Every argument is essentially a string. If it is a single identifier the quotes can be omitted.
Why not keep this convention? I'd vote for this.  (It's heavily inspired by "isar.")

If dropping this in favour of type safety, then probably this should be handled more strictly in order to not add confusion instead of removing it.

2025-02-22 10:23 UTC, mattulbrich commented on key.core/src/main/antlr4/KeYParser.g4
> +	( LBRACE sub=proofScript RBRACE SEMI?
Is this new?

2025-02-23 15:06 UTC, wadoon commented on key.core/src/main/antlr4/KeYParser.g4
> +	( LBRACE sub=proofScript RBRACE SEMI?
You mean that that `onAll { tryclose; }` would be now allowed yes. I allowed that proof script can receive a block of commands as an argument. Describe above in the "Additions to proof scripts". 

Better then to implement `onAll` my quirking around.

2025-03-07 20:57 UTC, mattulbrich commented
This PR seems to change the infrastructure quite considerably. It touches > 260 files, some of them rather far from the topic at hand.

I do like the idea to reuse the KeY parser instead of the handmade parser.
Still, there is nothing wrong (I think) with the character bases handmade parser, but the ANTLR machine of course allows for more flexibility and cleaner code.

I was not able to understand the higher order feature, but that looked nice indeed.

I'd argue against the (voluntary) strong typing. The design of the language is untyped. Everything is a string. I would like to stick to this on the KeY level. It is a different story on the JML level.

Can we break this down into manageable units (by cherrypicking aspects e.g.)?

The script proof engine can an overhaul if/when the JML scripts are on master-track.

2025-03-07 21:38 UTC, mattulbrich commented
Consider force pushing this to [`weigl/psg4-cleaned`](https://github.com/KeYProject/key/tree/weigl/psg4-cleaned) where most non-related aspects have been removed by rebasing the branch.

2025-03-07 23:50 UTC, mattulbrich commented
Afterwards consider https://github.com/KeYProject/key/tree/psg4-cleaned-continued where a few ideas from other branches regarding the non-JML bit of proof scripts have come together.

2025-03-07 23:54 UTC, mattulbrich commented
The ambiguity of the parser still is really a problem. `command a = b ==>` can be at least three different calls. Should ANTLR not complain? Parser generators usually have guarantees regarding ambiguities. ...

2025-03-12 17:22 UTC, wadoon commented
I'll rebase this PR. Splitting into multiple PRs should not only bring complexity.

2025-03-17 11:59 UTC, mattulbrich commented
Just read the commit message "Introduce ScriptCommandAst to keep the ProofEngine separated from ANT…"

I'd propose to limit this PR to its original purpose and merge it into master.
Going on from that point with ScriptCommandAPI etc is then up to further development in a next PR.
This would also allow to add new feature in other PRs.

2025-04-07 14:33 UTC, mattulbrich commented
You asked me for a review: What is the solution to the ambiguity problem again?

2025-04-11 17:10 UTC, wadoon commented on key.ui/examples/heap/quicksort/sort.key
> +\proofScript {
Reverted

2025-04-11 17:11 UTC, wadoon commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/wdFormulaRules.key
I am also not sure, when this came to this branch, but I thought we already fixed that on `main`.

2025-04-15 12:14 UTC, mattulbrich commented on key.core/src/main/antlr4/KeYParser.g4
> +  | term
Well this still has this ambiguity of "a=b" right?

I thought this should be a identifier, or perhaps a qualified identifier, right?

2025-04-15 12:19 UTC, mattulbrich commented on key.core/src/main/antlr4/KeYParser.g4
> +  | term
Or arguably even baseterm (without the infix operations)

2025-04-15 17:43 UTC, wadoon commented on key.core/src/main/antlr4/KeYParser.g4
> +  | term
```
  | abbreviation
  | accessterm
  | literals
```

Better? This prohibits also `macro split-prop;`.

2025-05-09 12:13 UTC, mattulbrich approved these changes

2025-05-09 13:22 UTC, merged