Lost rules: Seqperm, slice all taclet proofs
KeYProject/key pull request #3107
Opened 2023-04-06 13:06 UTC by jwiesler

* Fix some error reporting around `TacletProofObligationInput`
* Recover some lost (proven) rules involving `seqPerm`
* Slice all taclet proofs

2023-04-12 06:43 UTC, mattulbrich requested changes
There is an open question by the author:

> Edit 2: Slicing also deletes statistics like autoModeTime. Is there a way to keep those?

2023-04-12 06:43 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/seqPerm.key
> +    // Proven by ulbrich in isabell
Small comment. It's "Isabelle/HOL".

2023-04-12 19:00 UTC, jwiesler commented
The automode time is now being used for the newly created sliced proof.

2023-04-13 09:04 UTC, mattulbrich approved these changes

2023-04-13 13:49 UTC, merged