Fix for bug with effectless updates
KeYProject/key pull request #3205
Opened 2023-07-17 10:53 UTC by WolframPfeifer

This draft PR fixes a bug where updates are dropped even though they would have an effect. This happens since the DropEffectlessElementariesCondition performs the check using a LinkedHashSet, which relies on equals of LocationVariable. However, this is not implemented and defaults to equals of Object.

At the moment, I do not know why this bug only appears after pruning in the proof. Directly after opening/loading the instances of LocationVariable are the same, thus the check succeeds and the update is not dropped ...

Since the change might have a big impact, let's see if the tests run successfully.

2023-07-27 07:33 UTC, unp1 commented
> This draft PR fixes a bug where updates are dropped even though they would have an effect. This happens since the DropEffectlessElementariesCondition performs the check using a LinkedHashSet, which relies on equals of LocationVariable. However, this is not implemented and defaults to equals of Object.

That is strange. As LocationVariable is an Operator and operators are only considered equal if they are the same object, the defaulting to java.lang.Object's equals-method should be safe.

2023-07-27 07:45 UTC, unp1 commented
Thought a bit about it: The current fix would consider that two Locationvariable's are equal even if they are not the same Object. This hints that when pruning somehow the pruned back sequent got changed which could indicate some serious problem: 
either 

- somewhere the immutability of terms, programs or sequents got violated or 
- in case this happens only for a variable that is renamed before then the effectless sth. rule is applied (if that is the case, I might have fixed the problem coincidentally with PR #3224 (commit: [6b6f356b8](https://github.com/KeYProject/key/pull/3224/commits/6b6f356b869400b92b5aee3a0c6d5fff9d622c7b)

2023-07-28 06:54 UTC, FliegendeWurst commented
> Do you have an example (and short description) where I can reproduce the problem?

There is a simple example in #834.

2023-07-28 06:55 UTC, mattulbrich commented
@unp1, I think that #834 is indeed an example for the bug.

To me it seems that the invariant of the loop there refers to a local variable "test". However, there seem to be two different variables named test on two branches. I assume that the SpecificationRepository can only refer to one of them, thus the check might overlook it. (That's only a guess).

Still, the equal method for location variables does not fit the design principles chosen in KeY.

2023-07-28 07:05 UTC, mattulbrich requested changes

2023-07-28 07:05 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/logic/op/LocationVariable.java
> +    public boolean equals(Object obj) {
I think that KeY has been such that references to a program variable only refer to the same variable if they use the same location variable operator object.

If that is really to be changed, I really think the entire code base must be inspected to change this fundamental decision.

2023-07-28 07:08 UTC, mattulbrich commented
Richard @unp1 wrote:
> Thought a bit about it:  [...] Either
>     * somewhere the immutability of terms, programs or sequents got violated or

Exactly! This is what I assume is behind #3206 related to this problem. There in JmlAssert, there is a field which violates immutability. In #834, I assume that thanks to the specification repository, immutability is not necessarily guaranteed.(Or is it?)

2023-07-28 07:12 UTC, FliegendeWurst commented
> In https://github.com/KeYProject/key/issues/834, I assume that thanks to the specification repository, immutability is not necessarily guaranteed.(Or is it?)

The issue in #834 is that the LocationVariable is created twice by applying `methodBodyExpand` in different branches. Perhaps a better solution would be to store the location variables after expanding a method body and then try to reuse these objects when expanding the same method body in another branch.

2023-07-28 07:17 UTC, mattulbrich commented
> Perhaps a better solution would be to store the location variables after expanding a method body and then try to reuse these objects when expanding the same method body in another branch.

It would probable fix the issue in #834. There might also be several instances of the same modality on one sequent. (e.g. for info flow proof obligations). Would it be safe to reuse the existing program variable for both declarations. (It might be sound for valid Java programs. Is it?)

2023-07-28 07:22 UTC, unp1 commented
Hi, 
 I also co-assigned myself to this bug and will look into it. The specification repository should not be a problem w.r.t. immutability. When variables are renamed the renaming should be (and I think is) done on the loop invariant itself and then be registered in addition. Such that the old mapping origLoop -> origLoppInv and loopWithRenamedVariables -> loopInvWithRenamedVariables are registered. 
 
 When pruning, the original loop is back and the original loop invariant should be found. This would break with overwriting the equals method.

2023-07-28 07:26 UTC, mattulbrich commented
> The specification repository should not be a problem w.r.t. immutability. When variables are renamed the renaming should be (and I think is) done on the loop invariant itself and then be registered in addition. 

Thanks for the clarification, Richard @unp1. I wonder: If there are two branches with two different loop invariants for the same (object-identical) loop (b/c of symbolic execution), how does the repository know which loop invariant goes with which branch, or is the repository branch-local?

2023-07-28 07:32 UTC, unp1 commented
> Thanks for the clarification, Richard @unp1. I wonder: If there are two branches with two different loop invariants for the same (object-identical) loop (b/c of symbolic execution), how does the repository know which loop invariant goes with which branch, or is the repository branch-local?

That is a nice corner case and I have to look up if we had thought about it. At the moment I think it does not occur often as loops often have the same loop invariant and loops and loop invariants use local variables and method parameters. For these different variables are introduced on each branch and thus the loops are no longer equal on both branches.

2023-07-28 07:37 UTC, mattulbrich commented
Ah! So: It might be a not-so-bad solution to clone the method body prior
to method-body-statement execution? Then there are two different loop
objects (albeit holding the same content) that can have different loop
invariants.

I'd also like to clone JMLAssert statements on similar occasions (but
they have their condition locally)

2023-07-28 07:49 UTC, unp1 commented
Yes. Also at the moment I am wondering what happens in case we do a cut right before applying the loop invariant rule. Maybe we need to add some unique branch name as part of the KeY (or have the spec repository branch local).

2024-02-16 14:33 UTC, closed without merging