Handle bound variables in SMT unknown translation
KeYProject/key pull request #3263
Opened 2023-08-26 09:40 UTC by FliegendeWurst

Fixes #3262. There is still one TODO left in the code.

2023-09-19 07:37 UTC, mattulbrich requested changes
As discussed: The bound variables can be retrieved locally and need not be carried around so much.

2023-10-30 16:15 UTC, FliegendeWurst commented
Ready for review.

2023-11-24 13:41 UTC, mattulbrich approved these changes

2023-11-24 14:46 UTC, WolframPfeifer commented
For the future: Maybe we should update the comments generated for unknown symbols:
```
; --- Translation of unknown values
; unknown_0 :  seqDef{u:int}(Z(0(#)),seqLen(s),any::seqGet(s,u))
; unknown_1 :  seqDef{u:int}(Z(0(#)),seqLen(s1),any::seqGet(s1,u))
```
Since unknown_0 is a function, I would propose something like this:
```
; --- Translation of unknown values
; unknown_0(s:Seq) :  seqDef{u:int}(Z(0(#)),seqLen(s),any::seqGet(s,u))
; unknown_1 :  seqDef{u:int}(Z(0(#)),seqLen(s1),any::seqGet(s1,u))
```

2023-12-01 20:43 UTC, merged