Further Refactorings for Java 17+
KeYProject/key pull request #3264
Opened 2023-08-27 02:47 UTC by wadoon

* switch statements

2023-09-29 13:53 UTC, Drodt requested changes

2023-09-29 13:53 UTC, Drodt commented on key.core.rifl/src/main/java/de/uka/ilkd/key/util/rifl/RIFLHandler.java
Taking this as the example for all switch expressions: Why is the content of the switch not indented? I.e.:
```java
switch (localName) {
    case "sourcedompair", "source" -> startSource();
    ...
}
```

2023-09-29 14:07 UTC, wadoon commented on key.core.rifl/src/main/java/de/uka/ilkd/key/util/rifl/RIFLHandler.java
I just follow the formatting rules given by spotless. This might be question for @WolframPfeifer.

2023-10-05 06:25 UTC, unp1 commented on key.core.rifl/src/main/java/de/uka/ilkd/key/util/rifl/RIFLHandler.java
Checked the changes and they look fine from my side.

2023-10-12 19:26 UTC, Drodt approved these changes

2023-10-12 22:33 UTC, merged