Fix (for issue #3347) that node selection gets forgotten when switching between proofs
KeYProject/key pull request #3349
Opened 2023-11-13 18:53 UTC by unp1

2023-11-13 19:46 UTC, FliegendeWurst requested changes
Still broken, but now it only updates the sequent view to show a closed goal, and not the proof tree.

FWIW I fully expected these regressions when I originally made changes to the selection event handling in #3289. This area of KeY is extremely fragile.

2023-11-13 20:30 UTC, FliegendeWurst approved these changes
Issue is fixed. Code changes look good. But it is hard to check that all the removed setSelectedProof calls etc. were really not needed.

2023-11-13 20:30 UTC, FliegendeWurst commented on key.ui/src/main/java/de/uka/ilkd/key/core/KeYSelectionModel.java
> -    // TODO: remove usage of primary
Does this PR resolve the TODO?

2023-11-21 10:52 UTC, Drodt approved these changes

2023-11-21 11:56 UTC, merged