JML enabled keys indicator for the Status Line
KeYProject/key pull request #3374
Opened 2023-12-16 14:18 UTC by wadoon

Addition to #3373 which brings the following UI element: 

![image](https://github.com/KeYProject/key/assets/104259/0e5d2435-0813-4df9-b6d8-22bad3b21962)

2023-12-20 14:50 UTC, mattulbrich commented
Nice idea, but it looks a bit ugly as it is in the screenshot, doesn't it? Should read "Currently" in the tooltip.

2023-12-26 02:21 UTC, wadoon commented
Added more margin: 

![image](https://github.com/KeYProject/key/assets/104259/30842a60-16b2-4dc8-8d87-e468532433df)

2024-01-11 23:52 UTC, mattulbrich requested changes

2024-01-11 23:52 UTC, mattulbrich commented on key.ui/src/main/java/de/uka/ilkd/key/gui/JmlEnabledKeysIndicator.java
> +        lblIndicator.setToolTipText("Currently enabled keys for the JML condition evaluation");
How about: "Currently enabled keys for tool-specific JML annotations"

or is "JML condition evaluation" a technical term?

2024-01-11 23:52 UTC, mattulbrich commented on key.ui/src/main/java/de/uka/ilkd/key/gui/JmlEnabledKeysIndicator.java
> +    public List<JComponent> getStatusLineComponents() {
I'd have another small request: Following the design principle of the "dark cockpit philosophy", one should only indicate those things which are out of the ordinary. In 99.9% of the cases, we will use the default setting here. So it should be displayed, only if the deviate from the standard.

That would probably be just one if statement here.

2024-02-23 00:13 UTC, mattulbrich approved these changes

2024-02-23 01:19 UTC, merged