Fixed the path-to-smt-solver bug in windows
KeYProject/key pull request #3434
Opened 2024-02-29 10:18 UTC by vb213

## Intended Change
The specified path to a smt solver has been assembled incorrectly from the user input but still got cached in the proofIndependentSettings.props file. This caused a crash when restarting KeY. 
Now, 
1. the path is assembled correctly and
2. an invalid smt solver path in proofIndependentSettings.props will be ignored, thereby avoiding a crash on program start.

## Type of pull request

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (behaviour should not change or only minimally change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] There are changes to the (Java) code
- [ ] There are changes to the taclet rule base
- [ ] There are changes to the deployment/CI infrastructure (gradle, github, ...)
- [ ] Other: 

## Ensuring quality
    
- [ ] I made sure that introduced/changed code is well documented (javadoc and inline comments).
- [ ] I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- [ ] I added new test case(s) for new functionality.
- [ ] I have tested the feature as follows: ...
- [X ] I have checked that runtime performance has not deteriorated.

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

2024-03-11 10:27 UTC, FliegendeWurst requested changes
Thank you for your contribution. Please make sure your code follows the code formatting guidelines by running the spotlessApply gradle task. You can do so by executing `./gradlew key:spotlessApply` in the repository root.

2024-03-11 10:27 UTC, FliegendeWurst commented on key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/SMTSettingsProvider.java
> +import java.nio.file.InvalidPathException;
```suggestion
```

2024-03-11 10:27 UTC, FliegendeWurst commented on key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/SolverOptions.java
> +import java.nio.file.InvalidPathException;
```suggestion
```

2024-03-11 10:27 UTC, FliegendeWurst commented on key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/SolverOptions.java
> +
```suggestion

```

2024-03-11 10:27 UTC, FliegendeWurst commented on key.core/src/main/java/de/uka/ilkd/key/smt/SolverTypeCollection.java
> +import java.nio.file.InvalidPathException;
```suggestion
```

2024-03-11 10:27 UTC, FliegendeWurst commented on key.core/src/main/java/de/uka/ilkd/key/settings/ProofIndependentSMTSettings.java
> +import java.nio.file.InvalidPathException;
```suggestion
```

2024-03-11 10:27 UTC, FliegendeWurst commented on key.core/src/main/java/de/uka/ilkd/key/smt/SolverTypeCollection.java
> -
Please avoid unnecessary whitespace changes.

2024-04-20 09:59 UTC, wadoon approved these changes

2024-04-23 11:30 UTC, merged