Allow realizing multiple cached branches at once
KeYProject/key pull request #3440
Opened 2024-03-08 10:21 UTC by FliegendeWurst

## Intended Change

This PR changes the "Copy referenced proof steps here" action to allow applying it on any node that has leaf children with caching info.
It will then copy the referenced proof steps for all cached branches.

## Type of pull request

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (behaviour should not change or only minimally change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] There are changes to the (Java) code
- [ ] There are changes to the taclet rule base
- [ ] There are changes to the deployment/CI infrastructure (gradle, github, ...)
- [ ] Other: 

## Ensuring quality
    
- [ ] I made sure that introduced/changed code is well documented (javadoc and inline comments).
- [ ] I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- [ ] I added new test case(s) for new functionality.
- [x] I have tested the feature as follows: manual test (UI code)
- [ ] I have checked that runtime performance has not deteriorated.

## Additional information and contact(s)

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

2024-03-14 16:10 UTC, WolframPfeifer requested changes
This feature worked for me during review. Thanks! However, the user feedback should be improved a bit in my opinion: I nearly always get a dialog listing (only) the nodes where the caching failed (in the screenshot, actually two of the three goals are closed via cache):
![image](https://github.com/KeYProject/key/assets/94171076/8428e366-82f0-4af3-b1d7-8d4b783404cd)

A bit unrelated, I have another small feature request: "Prune Proof" should work with goals that are closed by cache. At the moment, I have to click on "Proof caching" -> "Re-open cached goal", which is a bit cumbersome. From a user point of view, both are the same operation (cutting away proof nodes).

2024-03-21 13:38 UTC, FliegendeWurst commented
> I nearly always get a dialog listing (only) the nodes where the caching failed (in the screenshot, actually two of the three goals are closed via cache):

I changed this dialog to list both successful matches and mismatches.

> A bit unrelated, I have another small feature request: "Prune Proof" should work with goals that are closed by cache.

Done

2026-06-18 16:51 UTC, WolframPfeifer commented
I just updated this to the new main branch. The changes in ProofPruner don't work (they seem to add an entry `null` to the list of open goals, which then later results in a NPE). This is also the cause for the test failure. Since the interaction between proof pruning and caching is a separate case (and seems to need a bigger fix), we should try to fix that in a separate PR.

I tested the rest of the functionality and it seems to work, with one small exception: The button in the status bar, which shows the number of cached goals, displays the wrong number after closing multiple cached goals via `Context menu --> Proof Caching --> Copy referenced proof steps here` (looks like the last number before closing - 1).

2026-06-18 17:13 UTC, WolframPfeifer commented
I removed the ProofPruner changes as they were broken, and made sure the UI (taskbar button) is updated.

2026-06-19 09:56 UTC, WolframPfeifer approved these changes

2026-06-19 11:27 UTC, merged