Weigl/pckgreworked
KeYProject/key pull request #3473
Opened 2024-05-24 21:45 UTC by wadoon

## Related Issue

This pull request addresses #.

## Intended Change

## Plan

* [ ] Implement feature 1
* [ ] Implement feature 2
* [ ] Code cleanup
* [ ] Document the changes

## Type of pull request

- Bug fix (non-breaking change which fixes an issue)
- Refactoring (behaviour should not change or only minimally change)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- There are changes to the (Java) code
- There are changes to the taclet rule base
- There are changes to the deployment/CI infrastructure (gradle, github, ...)
- Other: 

## Ensuring quality

    
- I made sure that introduced/changed code is well documented (javadoc and inline comments).
- I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- I added new test case(s) for new functionality.
- I have tested the feature as follows: ...
- I have checked that runtime performance has not deteriorated.

## Additional information and contact(s)

     

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

2025-03-07 18:08 UTC, WolframPfeifer requested changes
In general, I think it is a good idea to have disjoint packages for our (Gradle) submodules (i.e. `key.core`, `key.ui`, ...), even if we do not really use the module system at the moment.

Disabling the Ctrl+C signal handling is also fine, it was an experiment and apparently only worked correctly on some machines.

However, unfortunately there are the following blockers:

* Gradle task for GUI is not working, since build.gradle was not updated.
* Proof caching is completely disabled (?)

For a refactoring like this, I think you should have checked that everything works (at least a sanity check, i.e. running the KeY GUI once and see if the extensions are still there). In my opinion, this is not the task of the reviewer.

Minor remarks and open questions:
* Can you please update/complete the PR description? Otherwise, it is difficult to understand what this PR does exactly without looking into the code. Might also be relevant for the changelog ...
* I think the package name `de.uka.ilkd.key.ui.core` does not really make sense. Also, the separation between this, `de.uka.ilkd.key.ui`, and `de.uka.ilkd.key.gui` is not clear. If we are at restructuring, we should think of this as well.
* Is there any check/guarantee that the packages are actually disjoint now? It is really not obvious ...
* Can we prevent people from destroying disjointness accidentally in the future (for example, by adding a file in `key.ui` to package `de.uka.ilkd.key.core`)?

Thanks for the refactoring! If these points are resolved, it can be merged in my opinion.

2025-03-07 18:10 UTC, WolframPfeifer commented
Btw.: What do you mean by the label `breaks API`?

2025-03-10 13:17 UTC, wadoon commented
> Btw.: What do you mean by the label `breaks API`?

Breaks API indicates that a PR influences KeY's API and ABI. Hence, every downstream library, e.g., KeY4Eclipse, needs to be adopted---in this case, by changing the imports.

2025-05-10 15:54 UTC, wadoon commented on build.gradle
> +        maven { // remove if docking frames 1.1.3p2 on Maven Central
removed. entry was for a modularized version of docking frames.

2025-06-14 20:07 UTC, closed without merging