Restoration of the formatter for KeY files
KeYProject/key pull request #3494
Opened 2024-07-06 12:28 UTC by wadoon

Archeology: In the back old days, we reformatted all our KeY files. 

If you need to restore a branch before that time to bring it on the master, you should also reformat the KeY files before the merging. 

This PR brings the formatter written by Wiesler. 

The original MR was [!614](https://git.key-project.org/key/key/-/merge_requests/614).

Currently unclear, whether we want to bring this on the main.

**Has Sonarqube activated for evaluation reason**

* Missing for main 
  * [x] Test cases

2024-07-06 22:09 UTC, mattulbrich commented
Achieving auto-formatting for `.key` files would be nice since we have the infrastructure for this ...

2024-07-06 22:10 UTC, mattulbrich requested changes
There is no documentation / commenting at all.

2024-12-08 12:44 UTC, wadoon commented
@mattulbrich Looking in the test log shows, that not all KeY files in the repo are parsable anymore.

2025-01-24 20:06 UTC, wadoon commented
CodeBuff could be interesting here: https://www.antlr.org/papers/codebuff.pdf

2025-02-23 19:00 UTC, mattulbrich commented
This PR seems to also touch totally unrelated parts of the code. This is why it should not be merged as  is.
Does it make sense to  extract the actual formatter code and add that to the code base?

2025-02-23 23:01 UTC, wadoon commented
> This PR seems to also touch totally unrelated parts of the code. This is why it should not be merged as is. Does it make sense to extract the actual formatter code and add that to the code base?

I only see the necessary changes, and a lot of changes that arise by the fact, that the main is running away (spotless indentation changes, etc.)

2025-02-24 10:22 UTC, mattulbrich commented on key.format/src/test/java/CheckAll.java
> +        var s = Files.walk(Paths.get(".."));
Does this check all .key files in and under the key main directory? That would seem too strict.

2025-03-20 22:16 UTC, wadoon commented on key.format/src/test/java/CheckAll.java
> +        var s = Files.walk(Paths.get(".."));
is no limited to the rule base.

2025-03-20 23:53 UTC, wadoon commented
Formatter works now, but not on Windows. @mattulbrich

2025-03-31 15:22 UTC, wadoon commented on key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/GenerateUnitTests.java
> +        vars.put("baseDirectory", settings.getBaseDirectory().getAbsolutePath()
Required for Windows. :(

2025-04-03 15:53 UTC, mattulbrich commented on key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/GenerateUnitTests.java
> +        vars.put("baseDirectory", settings.getBaseDirectory().getAbsolutePath()
:( indeed. Why is this?

2025-04-03 15:57 UTC, mattulbrich commented
There is no documentation.

Can we add a README on the subproject toplevel explaining what this is for and what to do, how to configure etc.

2025-04-03 15:59 UTC, mattulbrich commented
Should it be part of the reformatting tasks? Would that not touch some gradle files in key.core?

2025-04-03 17:57 UTC, wadoon commented on key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/GenerateUnitTests.java
> +        vars.put("baseDirectory", settings.getBaseDirectory().getAbsolutePath()
I used `generateRAPUnit` on Windows. The different plattform (and Java NIO) resulted into file paths using `\\` and compile errors the backslashes were not escaped. 

Now, the code escapes backslashes.

2025-04-04 07:14 UTC, wadoon commented
> Should it be part of the reformatting tasks? Would that not touch some gradle files in key.core?

I wanted to keep the PR small. 

Normally, you want the formatter in spottless, but it is not obvious how todo it. I also fear the dependency when formatting requires compilation.

2025-10-11 22:54 UTC, wadoon commented
I abandon this PR. The original code does not work. 

I have pin down several formatting errors, until I reach now:

> Wrong pair [@172,1209:1209='(',<152>,37:19] closed by [@183,1284:1284='}',<155>,39:4] @ 

I do not want to track this any further.

@mattulbrich

2025-10-11 22:54 UTC, closed without merging