Improved treatment of final fields
KeYProject/key pull request #3495
Opened 2024-07-06 14:57 UTC by mattulbrich

## Intended Change

Final fields cannot change their value after a single assignment in the constructor. In the current KeY logic, final fields are treated like normal fields stored on the heap. This is highly inefficient since heap assignments cannot have an impact on final fields at all.

The plan is hence to access final fields using a function of their own that does not depend on the heap, unlike other fields

   T::select(Heap, Object, Field)   // for non-static fields
   T::final(Object, Field)  // for static fields

The major challenges include
- adapting reading of final fields in modalities
- adapting accessing final fields in JML
- handling constructors: they are allowed to write.

Writing must somehow be restricted since any modality could write to final fields and thus compromise proofs if thus different inconsistent values for final fields are around on a sequent.

## Plan

* [x] Add functions for finals, add a taclet option
* [x] Implement rules that act upon those taclet options
* [ ] Implement special treatment for constructors
* [ ] Test effectiveness
* [ ] Code cleanup
* [ ] Document the changes

## Type of pull request

- Breaking change (feature that cause existing functionality to change)

The plan is to have a taclet otion to fall back to old behaviour.

## Ensuring quality

To do:
 
- I made sure that introduced/changed code is well documented (javadoc and inline comments).
- I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- I added new test case(s) for new functionality.
- I have tested the feature as follows: ...
- I have checked that runtime performance has not deteriorated.

## Additional information and contact(s)

@WolframPfeifer @wadoon 

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

2024-07-06 19:27 UTC, wadoon commented
Is #3189 now obsolete?

Interestingly, `final` is not so final on [bytecode level](https://stackoverflow.com/questions/35319212/java-bytecode-final-field-assignment-jasmin).

2024-07-06 19:47 UTC, mattulbrich commented
> Is #3189 now obsolete?

This is the commits from back then merged onto the modern main.

> Interestingly, `final` is not so final on [bytecode level](https://stackoverflow.com/questions/35319212/java-bytecode-final-field-assignment-jasmin).

There are a few source code level things that get lost on byte code. Also generics. Sometimes private fields are not so private in byte code. We operate on source code level and assume that all code is compiler-conformant.

2024-12-10 11:38 UTC, mattulbrich commented
The last commits add sound special treatment for constructors.

2025-02-25 15:40 UTC, wadoon approved these changes

2025-02-25 15:40 UTC, wadoon commented on key.core/src/test/java/de/uka/ilkd/key/pp/FinalPrinterTest.java
> +    public static Stream<Arguments> casesWithFinal() {
You know that you can have this easier using `@CsvSource`?

2025-02-27 15:52 UTC, WolframPfeifer requested changes
Nice feature, while reviewing it everything worked as expected. I have a few minor questions/remarks that should be resolved, but overall I think it is very well written and also nicely documented in code. Thanks!

2025-02-27 15:52 UTC, WolframPfeifer commented on key.core/src/main/java/de/uka/ilkd/key/pp/FieldPrinter.java
> +            getJavaFieldConstant(fieldTerm, heapLDT, services);
I think the code here is correct, but really looks a bit weird (calling a getter, ignoring the result, and then returning true).

2025-02-27 15:52 UTC, WolframPfeifer commented on key.core/src/main/java/de/uka/ilkd/key/proof/init/FinalFieldCodeValidator.java
> +        // TODO We have to make sure that on non-static subclass is instantiated here
Open TODO? Honestly I don't understand it ...

2025-02-27 15:52 UTC, WolframPfeifer commented on key.core/src/main/java/de/uka/ilkd/key/proof/init/FinalFieldCodeValidator.java
> +                // TODO (well ... what about inner classes? Aren't they evil?)
What happens with inner classes in the current implementation?

2025-02-27 16:10 UTC, wadoon commented on key.core/src/test/java/de/uka/ilkd/key/pp/FinalPrinterTest.java
> +    public static Stream<Arguments> casesWithFinal() {
To who it may concern: 

https://mikemybytes.com/2021/10/19/parameterize-like-a-pro-with-junit-5-csvsource/

2025-02-27 17:29 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heapRules.key
> +                 boolean::select(h, o, java.lang.Object::<created>) = TRUE ==>)
Actually no. Final fields are considered to be constant throughout time not from a certain point onwards. We need to be able to activate objects. We could have two createdness flags (existing since beginning of the method and created during the call) with the former final and the latter not. But that not really simplify things, I fear.

2025-02-27 17:38 UTC, mattulbrich commented on key.core/src/test/java/de/uka/ilkd/key/pp/FinalPrinterTest.java
> +    public static Stream<Arguments> casesWithFinal() {
Well, I was under the same misconception as Wolfram that this would refer to an external .csv file.
With the csv data inline, it seems like a nice alternative.

2025-02-27 17:57 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/speclang/jml/translation/JMLSpecFactory.java
> +    /**
Yes. Ghost does not matter.

2025-02-27 18:01 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/javaRules.key
> +    // TODO 2 variants with different taclet options
You are right, that is missing the case distinction.

2025-02-27 18:01 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/pp/FieldPrinter.java
> +            getJavaFieldConstant(fieldTerm, heapLDT, services);
added comment

2025-02-27 18:01 UTC, mattulbrich commented on key.core/src/main/java/de/uka/ilkd/key/proof/init/FinalFieldsPOExtension.java
> +        assert iconstructor instanceof ProgramMethod : "Contracts cannot have schema ";
changed.

2025-02-27 18:02 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/optionsDeclarations.key
> +    /*!
copied to xml file.

2025-02-28 12:58 UTC, mattulbrich commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heap.key
> +    // reading from final attributes (corr. to select for non-final fields)
I spelled out "corresponds"

2025-02-28 13:05 UTC, WolframPfeifer commented on key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heap.key
> +    // reading from final attributes (corr. to select for non-final fields)
:see_no_evil: Ah, that makes sense. I just did not get it. Thanks for spelling it out.

2025-03-07 13:32 UTC, merged