Isabelle Translation
KeYProject/key pull request #3514
Opened 2024-09-05 12:01 UTC by BookWood7th

## Related Issue

This pull request addresses #.

## Intended Change
Adds a plugin, which allows the user to automatically translate a KeY sequent to an Isabelle theory and run parts of the automation of Isabelle on the translation. As presented at the KeY Symposium 2024

This broadens the automated toolset of KeY users, which allows for more automated proofs.

## Plan

* [x] Fix runaway Isabelle instances (Fixed as well as possible, due to the nature of the connection, Isabelle might still have runaway solvers)
* [x] Fix bugs in "stop" button used to interrupt Isabelle automation
* [-] Implement dedicated action to close goals (requires changes to core to be done correctly)
* [ ] Code cleanup and documentation
* [ ] Additional settings (timeout, automation tool selection etc.)
* [ ] Documentation for plugin interface
* [ ] Test cases
* [ ] Interactive proving in Isabelle

## Type of pull request

- Refactoring (behaviour should not change or only minimally change)
- New feature (non-breaking change which adds functionality)
- There are changes to the (Java) code

## Ensuring quality

    
- I made sure that introduced/changed code is well documented (javadoc and inline comments).
- I made sure that new/changed end-user features are well documented (https://github.com/KeYProject/key-docs).
- I added new test case(s) for new functionality.
- I have tested the feature as follows: ...
- I have checked that runtime performance has not deteriorated.

## Additional information and contact(s)

     

The contributions within this pull request are licensed under GPLv2 (only) for inclusion in KeY.

2025-02-12 16:34 UTC, WolframPfeifer commented
@BookWood7th What is the state of this PR? It is still marked as Draft, and out of date with main. If I remember correctly, it should be nearly main-ready. What is still missing?

2025-05-14 14:46 UTC, WolframPfeifer requested changes
Thank you for this nice addition to KeY!

I have only two minor points:
1) There are some classes (e.g., `ProofApplyUserAction`) which have a very generic name, but are Isabelle-specific. Can you please adapt the names?
(For the handlers, I think it is ok since this way it is immediately visible that they follow the same structure as the SMT handlers.)

2) Bug #3601 also exists for Isabelle, it should be easy to fix, I suggested an idea.

2025-05-14 14:46 UTC, WolframPfeifer commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/ProofApplyUserAction.java
> +public class ProofApplyUserAction extends UserAction {
I think this class should have a more descriptive name, e.g. "ProofApplyIsabellUserAction" (at least, Isabelle should be mentioned).

2025-05-14 14:46 UTC, WolframPfeifer commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/ProofApplyUserAction.java
> +    }
I just noticed that it has the same bug as SMT (#3601). I think the reason is that the code is taken and adapted from there. The solution should be easy: In addition to opening the goal, the last rule application has to be pruned. Can you take a look how it is done in `ProofModifyingUserAction` and fix it here? Then the fix should be easily transferrable to `ProofSMTApplyUserAction` to fix #3601.

2025-05-14 14:46 UTC, WolframPfeifer commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/controller/TranslateAllAction.java
> +public class TranslateAllAction extends MainWindowAction {
It is specific to Isabelle, so can you please mention that in the class name?

2025-05-14 14:46 UTC, WolframPfeifer commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/controller/TranslationAction.java
> +public class TranslationAction extends MainWindowAction {
Same name problem: Please mention Isabelle in the class name.

2025-05-16 09:19 UTC, BookWood7th commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/controller/TranslationAction.java
> +public class TranslationAction extends MainWindowAction {
New name: IsabelleTranslationAction

2025-05-16 09:19 UTC, BookWood7th commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/controller/TranslateAllAction.java
> +public class TranslateAllAction extends MainWindowAction {
New Name: IsabelleTranslateAllAction

2025-05-16 09:20 UTC, BookWood7th commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/ProofApplyUserAction.java
> +    }
I have fixed this bug. I have also created a PR #3606 to fix this for SMT

2025-05-16 09:20 UTC, BookWood7th commented on keyext.isabelletranslation/src/main/java/org/key_project/isabelletranslation/gui/ProofApplyUserAction.java
> +public class ProofApplyUserAction extends UserAction {
New Name: IsabelleProofApplyUserAction

2025-05-19 11:33 UTC, WolframPfeifer approved these changes
Thanks for fixing the undo bug! There is an ongoing discussion on how to best implement the undo operation in #3606, but I think this is a separate point. Since everything works here, it should be merged now.

2025-05-19 13:47 UTC, merged